return {
    -- "neovim/nvim-lspconfig",
    -- event = { "BufReadPre", "BufNewFile" },
    -- dependencies = {
    --     "hrsh7th/cmp-nvim-lsp",
    --     "mason-org/mason-lspconfig.nvim",
    -- },
    -- config = function()
    --     local cmp_nvim_lsp = require("cmp_nvim_lsp")
    --
    --     vim.api.nvim_create_autocmd("LspAttach", {
    --         group = vim.api.nvim_create_augroup("UserLspConfig", {}),
    --         callback = function(ev) end,
    --     })
    --
    --     local capabilities = cmp_nvim_lsp.default_capabilities()
    --     local on_attach = function(_, bufnr)
    --         opts.buffer = bufnr
    --     end
    --
    --     vim.lsp.config("volar", {
    --         on_attach = on_attach,
    --         capabilities = capabilities,
    --         filetypes = { "typescript", "javascript", "javascriptreact", "typescriptreact", "vue" },
    --         init_options = {
    --             vue = {
    --                 hybridMode = false,
    --             },
    --             typescript = {
    --                 tsdk = vim.fn.stdpath("data") .. "/mason/packages/vue-language-server/node_modules/typescript/lib/",
    --             },
    --         },
    --     })
    --
    --     vim.lsp.enable({ "volar" })
    -- end,
}
